server:
  port: 8088


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #netty 路由过滤器，http或https开头
        - id: app1-route
          uri: http://localhost:8093
          predicates:
            - Path=/consumer/**
          filters:
            #转发请求时去掉1级前缀
            - StripPrefix=1
        - id: api-bb
          uri: http://localhost:8091
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1